# Generated by Django 3.1.7 on 2021-04-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_api', '0003_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
    ]
