# Generated by Django 3.1.7 on 2021-04-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_api', '0006_twitterfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterfollower',
            name='follower',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='follower_user', to='tweet_api.user'),
        ),
        migrations.AddField(
            model_name='twitterfollower',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='tweet_api.user'),
        ),
    ]
