# Generated by Django 3.1.7 on 2021-04-13 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_api', '0004_tweet_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweeted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tweet_api.user'),
        ),
    ]
