# Generated by Django 3.1.7 on 2021-04-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_content', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('active_status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tweet_webhook',
                'managed': True,
            },
        ),
    ]
