# Generated by Django 3.1.7 on 2021-04-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetwebhook',
            name='webhook_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
