# Generated by Django 3.1.7 on 2021-04-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_webhook', '0002_auto_20210423_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashtagWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_content', models.TextField(blank=True, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=255, null=True)),
                ('active_status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'hashtag_webhook',
                'managed': True,
            },
        ),
    ]
